#!/usr/bin/env python3
"""
Daily Verdict Page Generator

Reads data/regime.json + data/meta.json + data/btc_price.json
and generates an indexable HTML page at verdicts/YYYY-MM-DD/index.html.

Called by collect.py after data collection. Only generates once per day.
Also updates verdicts/index.html (archive landing) with the new entry.
"""
import json
import os
from datetime import datetime, timezone
from pathlib import Path

BASE = Path(__file__).parent.parent
DATA = BASE / "data"
VERDICTS_DIR = BASE / "verdicts"


def read_json(path):
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return None


def verdict_class(verdict):
    v = (verdict or "").upper()
    if "BULL" in v and "CAUTIOUS" not in v:
        return "bull"
    elif "BEAR" in v or "DO NOT" in v:
        return "bear"
    elif "ABORT" in v:
        return "abort"
    return "neutral"


def generate_verdict_page():
    """Generate today's verdict page if it doesn't exist yet."""
    regime = read_json(DATA / "regime.json")
    meta = read_json(DATA / "meta.json")
    btc = read_json(DATA / "btc_price.json")

    if not regime or not regime.get("synthesis"):
        return False

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    today_display = datetime.now(timezone.utc).strftime("%B %d, %Y")
    verdict_dir = VERDICTS_DIR / today
    verdict_file = verdict_dir / "index.html"

    # Only generate once per day
    if verdict_file.exists():
        return False

    verdict_dir.mkdir(parents=True, exist_ok=True)

    synthesis = regime.get("synthesis", {})
    verdict = synthesis.get("verdict", "UNKNOWN")
    detail = synthesis.get("detail", "")
    vclass = verdict_class(verdict)

    btc_price = btc.get("price") if btc else meta.get("btc_price")
    price_str = f"${btc_price:,.0f}" if btc_price else "N/A"

    # Build layer breakdown
    layers = []
    layer_names = {
        "gate": "Gate0",
        "macro": "Macro",
        "structure": "Structure",
        "derivatives": "Derivatives",
        "cycle": "Cycle",
    }
    for key, name in layer_names.items():
        layer = regime.get(key, {})
        v = layer.get("verdict", "—")
        d = layer.get("detail", "")
        emoji = layer.get("emoji", "")
        layers.append(f"<tr><td><strong>{name}</strong></td><td>{emoji} {v}</td><td>{d}</td></tr>")

    # Build reasoning narrative
    reasoning = f"On {today_display}, the Gate0 pipeline risk synthesis was {verdict}. {detail}"
    if synthesis.get("ta_warning"):
        reasoning += f" Technical analysis warning: {synthesis['ta_warning']}."
    if synthesis.get("manual_override", {}).get("active"):
        mo = synthesis["manual_override"]
        reasoning += f" Manual override active: {mo.get('status')} — {mo.get('reason', '')}."

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Bitcoin Market Report — {today_display} | Pipeline Dashboard</title>
<meta name="description" content="On {today_display}, the Gate0 pipeline risk synthesis was {verdict}. See the full 5-layer analysis, metrics snapshot, and reasoning. BTC at {price_str}.">
<link rel="canonical" href="https://aikeluargalee-tech.github.io/pipeline-dashboard-v2/verdicts/{today}/">
<meta property="og:title" content="Bitcoin Market Report — {today_display}">
<meta property="og:type" content="article">
<meta property="og:description" content="Gate0 risk synthesis: {verdict}. Full 5-layer Bitcoin analysis for {today_display}.">
<script type="application/ld+json">
{{
  "@context": "https://schema.org",
  "@type": "Article",
  "headline": "Bitcoin Market Report — {today_display}",
  "datePublished": "{today}",
  "dateModified": "{today}",
  "description": "Gate0 risk synthesis: {verdict}. {detail[:150]}",
  "url": "https://aikeluargalee-tech.github.io/pipeline-dashboard-v2/verdicts/{today}/"
}}
</script>
<link rel="stylesheet" href="../../assets/styles.css">
</head>
<body>
<div id="nav-placeholder"></div>

<main class="page-container">
  <div class="breadcrumb"><a href="../../">Home</a><span>›</span> <a href="../">Reports</a><span>›</span> {today_display}</div>

  <article class="article-body">
    <h1>Bitcoin Market Report — {today_display}</h1>
    <div class="article-meta">BTC: {price_str} · Generated by Gate0 Pipeline</div>

    <div style="text-align:center;margin:32px 0">
      <span class="verdict-badge {vclass}" style="font-size:1.4em;padding:12px 32px">{verdict}</span>
    </div>

    <h2>Layer Breakdown</h2>
    <table class="verdict-table">
      <thead><tr><th>Layer</th><th>Risk Parameter</th><th>Detail</th></tr></thead>
      <tbody>
        {chr(10).join(layers)}
      </tbody>
    </table>

    <h2>Reasoning</h2>
    <p>{reasoning}</p>

    <h2>Metrics Snapshot</h2>
    <ul>
      <li><strong>BTC Price:</strong> {price_str}</li>
      <li><strong>Bull signals:</strong> {synthesis.get('bull_count', '?')}</li>
      <li><strong>Bear signals:</strong> {synthesis.get('bear_count', '?')}</li>
      <li><strong>TA warning:</strong> {synthesis.get('ta_warning', 'None')}</li>
    </ul>

    <h2>Outcome Tracking</h2>
    <div class="callout info">
      <strong>Pending:</strong>
      This risk synthesis will be evaluated 7 days from generation. Did BTC move in the predicted direction?
    </div>

    <div style="margin-top:40px;display:flex;gap:12px;justify-content:center">
      <a href="../../dashboard/" class="cta-button primary">Live Dashboard →</a>
      <a href="../../methodology/" class="cta-button secondary">How Risk Models Work</a>
    </div>
  </article>
</main>

<div id="footer-placeholder"></div>
<script src="../../assets/nav.js"></script>
</body>
</html>
"""

    # Atomic write
    tmp = verdict_file.with_name(f".{verdict_file.name}.tmp")
    with open(tmp, "w") as f:
        f.write(html)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, verdict_file)

    # Update archive index
    update_archive_index(today, today_display, verdict, vclass, btc_price)

    return True


def update_archive_index(today, today_display, verdict, vclass, btc_price):
    """Update verdicts/index.html with the new entry."""
    price_str = f"${btc_price:,.0f}" if btc_price else "N/A"

    # Read existing entries
    archive_file = VERDICTS_DIR / "index.html"
    entries = []

    if archive_file.exists():
        with open(archive_file) as f:
            content = f.read()
        # Extract existing entries from the table
        import re
        for m in re.finditer(r'<tr>\s*<td><a href="([^"]+)">([^<]+)</a></td>\s*<td><span class="verdict-badge ([^"]+)">([^<]+)</span></td>\s*<td>([^<]*)</td>\s*</tr>', content):
            entries.append({
                "url": m.group(1),
                "date": m.group(2),
                "vclass": m.group(3),
                "verdict": m.group(4),
                "price": m.group(5),
            })

    # Add today's entry at the top
    new_entry = {
        "url": f"{today}/",
        "date": today_display,
        "vclass": vclass,
        "verdict": verdict,
        "price": price_str,
    }
    # Remove duplicate if exists
    entries = [e for e in entries if e["url"] != new_entry["url"]]
    entries.insert(0, new_entry)

    # Build table rows
    rows = []
    for e in entries[:90]:  # Keep last 90 days
        rows.append(f"""        <tr>
          <td><a href="{e['url']}">{e['date']}</a></td>
          <td><span class="verdict-badge {e['vclass']}">{e['verdict']}</span></td>
          <td>{e['price']}</td>
        </tr>""")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Daily Report Archive — Bitcoin Market History | Pipeline Dashboard</title>
<meta name="description" content="Every daily Bitcoin market risk synthesis from the Gate0 pipeline, archived with full reasoning, metrics snapshot, and outcome tracking.">
<link rel="canonical" href="https://aikeluargalee-tech.github.io/pipeline-dashboard-v2/verdicts/">
<meta property="og:title" content="Daily Report Archive — Bitcoin Market History">
<meta property="og:type" content="website">
<link rel="stylesheet" href="../assets/styles.css">
</head>
<body>
<div id="nav-placeholder"></div>

<main class="page-container">
  <div class="breadcrumb"><a href="../">Home</a><span>›</span> Reports</div>

  <h1 style="font-size:2em;font-weight:800;margin-bottom:8px">Daily Report Archive</h1>
  <p style="color:var(--muted);margin-bottom:32px">Every market report, stored with full 5-layer breakdown, metrics snapshot, and reasoning. Outcome tracking shows whether the risk synthesis played out correctly.</p>

  <table class="verdict-table">
    <thead>
      <tr><th>Date</th><th>Risk Parameter</th><th>BTC Price</th></tr>
    </thead>
    <tbody>
{chr(10).join(rows)}
    </tbody>
  </table>

  <div class="newsletter-section">
    <h3>📬 Get the Daily Market Report</h3>
    <p>Bitcoin market report delivered to your inbox every day. No spam, unsubscribe anytime.</p>
    <form class="newsletter-form" action="https://buttondown.email/api/emails/embed-subscribe/btcpipeline" method="post" target="popupwindow">
      <input type="email" name="email" placeholder="your@email.com" required aria-label="Email address">
      <button type="submit">Subscribe</button>
    </form>
  </div>
</main>

<div id="footer-placeholder"></div>
<script src="../assets/nav.js"></script>
</body>
</html>
"""

    VERDICTS_DIR.mkdir(parents=True, exist_ok=True)
    tmp = archive_file.with_name(f".{archive_file.name}.tmp")
    with open(tmp, "w") as f:
        f.write(html)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, archive_file)


if __name__ == "__main__":
    result = generate_verdict_page()
    if result:
        print(f"✅ Verdict page generated for {datetime.now(timezone.utc).strftime('%Y-%m-%d')}")
    else:
        print("ℹ️  Verdict page already exists for today or data unavailable")
